version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "3001:3001"
    environment:
      - MONGO_URI=mongodb://mongodb_new:27017/devopsdata
    depends_on:
      - mongo



  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"



  mongo:
    image: mongo:latest
    container_name: mongodb_new
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db





volumes:
  mongo_data:

